### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by bigpowermind** [bigpowermind/fleamarket_sample_78a#18]
■ URL
IPアドレス：http://18.182.74.43/
Github（最終課題のリポジトリ）：https://github.com/bigpowermind/fleamarket_sample_78a

■ Basic認証
ID：daifuku
Pass：daifuku78a

■ テスト用アカウント
◯ 購入者用
メールアドレス：sample102@sample.com
パスワード： buyer1234

◯ 購入用カード情報
番号:4242424242424242
期限:12/24
セキリュティカード:123

◯ 出品者用
メールアドレス: sample101@sample.com
パスワード: seller1234

**Comment by div-shibata** [comment]
大力さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・出品者用、購入者用どちらもログインできませんでした。メールアドレスとパスワードに不備がないか確認をお願いします。
・basic認証がうまく作動していないようです。
・少なくとも３品以上の出品をお願いします

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by bigpowermind** [comment]
修正しました。
よろしくお願いします。

**Comment by div-shibata** [comment]
大力さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※挙動は問題ございませんでしたが、就職活動で使用される際に訂正しておくとよい箇所が1点ございました。
商品購入画面でカードを登録していても、「カードを登録してください」「支払い方法の入力を完了してください」の表示がでます。実際に購入はできるためLGTMとしましたが、余裕があれば表示されないよう修正されるといいかと思います。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by bigpowermind** [comment]
有り難うございます！！！
